config/routes.rb
Rails.application.routes.draw do
  get 'jirous/create'
  get 'jirous/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'users/index'
  get 'notifications/index'
  get 'microposts/index'
  
  
  get 'jirous/post'
  post 'jirous/word'
  get 'jirous/word', to: 'jirous#search'
  get 'jirous/search'
  post 'jirous/create'
  get 'jirous/shoplist'
  get 'jirous/wordlist'
  delete 'jirous/:id' , to: 'jirous#destroy'

  root to: "home#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :comments, only: [:create] 
  end
  resources :microposts,only: [:index, :show, :create, :destroy, :edit] do
  resources :likes, only: [:create, :destroy]
  end
  resources :notifications, only: :index
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, { :previous_label => '&lt 前へ', :next_label => '次へ &gt' } %>
<% end %>

app/views/shared/_header.html.erb
<ul class="nav">
  ~
  <li class="notification"><%=link_to '通知', notifications_path, class:"btn"  %>
  <% if unchecked_notifications.any? %>
    <i class="fa fa-circle notification-circle"></i>
  <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "何かつぶやく" %>
  </div>
  <%= f.submit "つぶやく！", class: "btn btn-primary" %>
  
  <span class="img">
    <%= f.file_field :img, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  
<% end %>

app/views/shared/_myjirou.html.erb
<h3> my メシ </h3>
<% unless @user.jirous.empty? %>
  <% @user.jirous.each do |shop| %>

    <div><%= link_to shop.name, "#{shop.url}" %> 
        <%= link_to '削除', "/jirous/#{shop.id.to_i}", method: :delete,  data: { confirm: "削除してよろしいですか？", commit: "削除する", cancel: "やめる", title: "ご確認ください" }, :style=>"color:red; font-size:10px;" %></div>
    <div><%= link_to image_tag("#{shop.image_url}"), "#{shop.url}" %></div>
  <% end %>
<% end %>

app/views/shared/_notifications.html.erb
<div class="notificationbar">
<ul class="nav">
  ~
  <li class="notification"><%=link_to '通知', notifications_path, class:"btn"  %>
  <% if unchecked_notifications.any? %>
    <i class="fa fa-circle notification-circle"></i>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "プロフィールを見る", current_user %></span>
<span><%= current_user.microposts.count %>のつぶやき</span>